/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import PomocneKlase.Validation;
import RadSBazom.Address;
import RadSBazom.Contact;
import RadSBazom.Record;
import RadSBazom.SelectIzBaze;
import RadSBazom.UpdateSBazom;
import RadSBazom.UpisivanjeUBazu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Bruno-PC
 */
public class GUICRF extends javax.swing.JFrame {

    /**
     * Creates new form GUICRF
     */
    Validation valid = new Validation();
    UpisivanjeUBazu upis = new UpisivanjeUBazu();
    UpdateSBazom upisUpdate = new UpdateSBazom();
    SelectIzBaze selectIzBaze = new SelectIzBaze();

    public GUICRF() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        errorKucniBrojPrivremena = new javax.swing.JLabel();
        errorUlicaPrivremena = new javax.swing.JLabel();
        errorKvartPrivremeni = new javax.swing.JLabel();
        errorGradPrivremeni = new javax.swing.JLabel();
        errorDrzavaPrivremena = new javax.swing.JLabel();
        errorPostanskiBrojPrivremeni = new javax.swing.JLabel();
        errorKucniBrojStalni = new javax.swing.JLabel();
        errorUlicaStalna = new javax.swing.JLabel();
        errorKvartStalni = new javax.swing.JLabel();
        errorGradStalni = new javax.swing.JLabel();
        errorDrzavaStalna = new javax.swing.JLabel();
        errorPostanskiBrojStalni = new javax.swing.JLabel();
        errorBrojTelefonaPosaoPacijent = new javax.swing.JLabel();
        errorBrojTelefonaKucniPacijent = new javax.swing.JLabel();
        errorBrojMobitelaPacijent = new javax.swing.JLabel();
        errorFaxPacijenta = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        errorIDPacijent = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtIDPacijenta = new javax.swing.JTextField();
        txtKucniBrojPrivremeni = new javax.swing.JTextField();
        txtUlicaPrivremena = new javax.swing.JTextField();
        txtKvartPrivremeni = new javax.swing.JTextField();
        txtGradPrivremeni = new javax.swing.JTextField();
        txtDrzavaPrivremena = new javax.swing.JTextField();
        txtPostanskiBrojPrivremeni = new javax.swing.JTextField();
        txtKucniBrojStalni = new javax.swing.JTextField();
        txtUlicaStalna = new javax.swing.JTextField();
        txtKvartStalni = new javax.swing.JTextField();
        txtGradStalni = new javax.swing.JTextField();
        txtDrzavaStalna = new javax.swing.JTextField();
        txtPostanskiBrojStalni = new javax.swing.JTextField();
        txtBrojTelefonaPosaoPacijenta = new javax.swing.JTextField();
        txtBrojTelefonaKucniPacijenta = new javax.swing.JTextField();
        txtBrojMobitelaPacijenta = new javax.swing.JTextField();
        txtPagerPacijenta = new javax.swing.JTextField();
        txtKucniBrojRodaka = new javax.swing.JTextField();
        txtUlicaRodaka = new javax.swing.JTextField();
        txtKvartRodaka = new javax.swing.JTextField();
        txtGradRodaka = new javax.swing.JTextField();
        txtDrzavaRodaka = new javax.swing.JTextField();
        txtPostanskiBrojRodaka = new javax.swing.JTextField();
        txtBrojTelefonaPosaoRodak = new javax.swing.JTextField();
        txtBrojTelefonaKucniRodak = new javax.swing.JTextField();
        txtBrojMobitelaRodak = new javax.swing.JTextField();
        txtPagerRodak = new javax.swing.JTextField();
        txtFaxRodak = new javax.swing.JTextField();
        txtBracniStatus = new javax.swing.JTextField();
        txtBrojLjudiKojeUzdrazavate = new javax.swing.JTextField();
        txtVisina = new javax.swing.JTextField();
        txtTezina = new javax.swing.JTextField();
        txtKrvnaGrupa = new javax.swing.JTextField();
        txtZanimanje = new javax.swing.JTextField();
        txtBrutoDrustveniDohodak = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        txtFaxPacijenta = new javax.swing.JTextField();
        errorPagerPacijent = new javax.swing.JLabel();
        errorKucniBrojRodak = new javax.swing.JLabel();
        errorUlicaRodak = new javax.swing.JLabel();
        errorKvartRodak = new javax.swing.JLabel();
        errorGradRodak = new javax.swing.JLabel();
        errorDrzavaRodak = new javax.swing.JLabel();
        errorPostanskiBrojRodak = new javax.swing.JLabel();
        errorBrojTelefonaPosaoRodak = new javax.swing.JLabel();
        errorBrojTelefonaKucniRodak = new javax.swing.JLabel();
        errorBrojMobitelaRodak = new javax.swing.JLabel();
        errorPagerRodak = new javax.swing.JLabel();
        errorFaxRodak = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        boxVegeterijanac = new javax.swing.JCheckBox();
        errorBracniStatus = new javax.swing.JLabel();
        errorBrojLjudiKojeUzdrzavate = new javax.swing.JLabel();
        errorVisinađ = new javax.swing.JLabel();
        errorTezina = new javax.swing.JLabel();
        errorKrvnaGrupa = new javax.swing.JLabel();
        errorZanimanje = new javax.swing.JLabel();
        errorBrutoGodisnjiDohodak = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        boxPusac = new javax.swing.JCheckBox();
        boxAlkohol = new javax.swing.JCheckBox();
        boxStimulansi = new javax.swing.JCheckBox();
        boxDijabeticar = new javax.swing.JCheckBox();
        boxRedovniObroci = new javax.swing.JCheckBox();
        boxHipersenzitivan = new javax.swing.JCheckBox();
        txtBrojCigareta = new javax.swing.JTextField();
        txtAlkohol = new javax.swing.JTextField();
        txtStimulansi = new javax.swing.JTextField();
        txtKavaCaj = new javax.swing.JTextField();
        txtBezalkoholnaPica = new javax.swing.JTextField();
        txtDomaVani = new javax.swing.JTextField();
        txtStanjeSrca = new javax.swing.JTextField();
        txtStanjeDisnogPuta = new javax.swing.JTextField();
        txtStanjeProbanogSustava = new javax.swing.JTextField();
        txtOrtopedskoStanje = new javax.swing.JTextField();
        txtStanjeMisica = new javax.swing.JTextField();
        txtMentalnoStanje = new javax.swing.JTextField();
        txtAlergije = new javax.swing.JTextField();
        txtReakcije = new javax.swing.JTextField();
        txtPrijasnjeOperacije = new javax.swing.JTextField();
        errorBrojCigareta = new javax.swing.JLabel();
        errorAlkohol = new javax.swing.JLabel();
        errorStimulansi = new javax.swing.JLabel();
        errorKavaCaj = new javax.swing.JLabel();
        errorBezalkoholnaPica = new javax.swing.JLabel();
        errorDomaVani = new javax.swing.JLabel();
        errorSrce = new javax.swing.JLabel();
        errorDisniSustav = new javax.swing.JLabel();
        errorProbavniSustav = new javax.swing.JLabel();
        errorOrtopedskoStanje = new javax.swing.JLabel();
        errorStanjeMisica = new javax.swing.JLabel();
        errorMentalnoStanje = new javax.swing.JLabel();
        errorAlergije = new javax.swing.JLabel();
        errorReakcije = new javax.swing.JLabel();
        errorOperacije = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        errorZalbeBolovi = new javax.swing.JLabel();
        errorPrijasnjiTretmani = new javax.swing.JLabel();
        errorPrijasnji = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtZalbeBolovi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTretman = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDoktorBolnica = new javax.swing.JTextArea();
        errorUpisaSvega = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel67 = new javax.swing.JLabel();
        errorEmailPacijent = new javax.swing.JLabel();
        txtEmailPacijenta = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        errorEmailRodaka = new javax.swing.JLabel();
        txtEmailRodaka = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRF");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("IDPacijenta");
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("Privremena adresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Kucni broj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Ulica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Kvart");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("Grad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setText("Drzava");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("Postanski broj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("Stalna adresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setText("Kucni broj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        getContentPane().add(jLabel10, gridBagConstraints);

        jLabel11.setText("Ulica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        getContentPane().add(jLabel11, gridBagConstraints);

        jLabel12.setText("Kvart");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        getContentPane().add(jLabel12, gridBagConstraints);

        jLabel13.setText("Grad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        getContentPane().add(jLabel13, gridBagConstraints);

        jLabel14.setText("Drzava");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        getContentPane().add(jLabel14, gridBagConstraints);

        jLabel15.setText("Postanski broj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        getContentPane().add(jLabel15, gridBagConstraints);

        jLabel16.setText("Kontakt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jLabel16, gridBagConstraints);

        jLabel17.setText("Broj telefona(posao)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        getContentPane().add(jLabel17, gridBagConstraints);

        jLabel18.setText("Broj telefona(kucni)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        getContentPane().add(jLabel18, gridBagConstraints);

        jLabel19.setText("Broj mobitela");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        getContentPane().add(jLabel19, gridBagConstraints);

        jLabel20.setText("Pager");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        getContentPane().add(jLabel20, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        getContentPane().add(errorKucniBrojPrivremena, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(errorUlicaPrivremena, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        getContentPane().add(errorKvartPrivremeni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(errorGradPrivremeni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        getContentPane().add(errorDrzavaPrivremena, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        getContentPane().add(errorPostanskiBrojPrivremeni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        getContentPane().add(errorKucniBrojStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        getContentPane().add(errorUlicaStalna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        getContentPane().add(errorKvartStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        getContentPane().add(errorGradStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        getContentPane().add(errorDrzavaStalna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        getContentPane().add(errorPostanskiBrojStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        getContentPane().add(errorBrojTelefonaPosaoPacijent, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        getContentPane().add(errorBrojTelefonaKucniPacijent, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        getContentPane().add(errorBrojMobitelaPacijent, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        getContentPane().add(errorFaxPacijenta, gridBagConstraints);

        jLabel40.setText("Kucni broj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel40, gridBagConstraints);

        jLabel41.setText("Ulica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel41, gridBagConstraints);

        jLabel42.setText("Kvart");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel42, gridBagConstraints);

        jLabel43.setText("Grad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel43, gridBagConstraints);

        jLabel44.setText("Drzava");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel44, gridBagConstraints);

        jLabel45.setText("Postanski broj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jLabel45, gridBagConstraints);

        jLabel46.setText("Broj telefona(posao)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        getContentPane().add(jLabel46, gridBagConstraints);

        jLabel47.setText("Kontakt rodaka");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jLabel47, gridBagConstraints);

        jLabel48.setText("Broj telefona(kucni)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        getContentPane().add(jLabel48, gridBagConstraints);

        jLabel49.setText("Broj mobitela");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        getContentPane().add(jLabel49, gridBagConstraints);

        jLabel50.setText("Pager");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        getContentPane().add(jLabel50, gridBagConstraints);

        jLabel51.setText("Fax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        getContentPane().add(jLabel51, gridBagConstraints);

        jLabel52.setText("Bracni status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        getContentPane().add(jLabel52, gridBagConstraints);

        jLabel53.setText("Broj ljudi koje uzdrzavate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        getContentPane().add(jLabel53, gridBagConstraints);

        jLabel54.setText("Visina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        getContentPane().add(jLabel54, gridBagConstraints);

        jLabel55.setText("Tezina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        getContentPane().add(jLabel55, gridBagConstraints);

        jLabel56.setText("Krvna grupa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        getContentPane().add(jLabel56, gridBagConstraints);

        jLabel57.setText("Zanimanje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        getContentPane().add(jLabel57, gridBagConstraints);

        jLabel58.setText("Bruto godisnji dohodak");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        getContentPane().add(jLabel58, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        getContentPane().add(errorIDPacijent, gridBagConstraints);

        jLabel60.setText("Adresa rodaka");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jLabel60, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtIDPacijenta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtKucniBrojPrivremeni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        getContentPane().add(txtUlicaPrivremena, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtKvartPrivremeni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtGradPrivremeni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtDrzavaPrivremena, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtPostanskiBrojPrivremeni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtKucniBrojStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtUlicaStalna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtKvartStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtGradStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtDrzavaStalna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtPostanskiBrojStalni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrojTelefonaPosaoPacijenta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrojTelefonaKucniPacijenta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrojMobitelaPacijenta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtPagerPacijenta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        getContentPane().add(txtKucniBrojRodaka, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtUlicaRodaka, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtKvartRodaka, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtGradRodaka, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtDrzavaRodaka, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtPostanskiBrojRodaka, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrojTelefonaPosaoRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrojTelefonaKucniRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrojMobitelaRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtPagerRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtFaxRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBracniStatus, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrojLjudiKojeUzdrazavate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtVisina, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtTezina, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtKrvnaGrupa, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtZanimanje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBrutoDrustveniDohodak, gridBagConstraints);

        jLabel61.setText("Fax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        getContentPane().add(jLabel61, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtFaxPacijenta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 19;
        getContentPane().add(errorPagerPacijent, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        getContentPane().add(errorKucniBrojRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        getContentPane().add(errorUlicaRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        getContentPane().add(errorKvartRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        getContentPane().add(errorGradRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        getContentPane().add(errorDrzavaRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        getContentPane().add(errorPostanskiBrojRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        getContentPane().add(errorBrojTelefonaPosaoRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        getContentPane().add(errorBrojTelefonaKucniRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        getContentPane().add(errorBrojMobitelaRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        getContentPane().add(errorPagerRodak, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        getContentPane().add(errorFaxRodak, gridBagConstraints);

        jLabel21.setText("Vegetarijanac");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 21;
        getContentPane().add(jLabel21, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 21;
        getContentPane().add(boxVegeterijanac, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        getContentPane().add(errorBracniStatus, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        getContentPane().add(errorBrojLjudiKojeUzdrzavate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        getContentPane().add(errorVisinađ, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 17;
        getContentPane().add(errorTezina, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        getContentPane().add(errorKrvnaGrupa, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 19;
        getContentPane().add(errorZanimanje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        getContentPane().add(errorBrutoGodisnjiDohodak, gridBagConstraints);

        jLabel22.setText("Prijasnje operacije");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 20;
        getContentPane().add(jLabel22, gridBagConstraints);

        jLabel23.setText("Reakcije na specificne lijekove");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 19;
        getContentPane().add(jLabel23, gridBagConstraints);

        jLabel24.setText("Alergije");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 18;
        getContentPane().add(jLabel24, gridBagConstraints);

        jLabel25.setText("Mentalno stanje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 17;
        getContentPane().add(jLabel25, gridBagConstraints);

        jLabel26.setText("Stanje misica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 16;
        getContentPane().add(jLabel26, gridBagConstraints);

        jLabel27.setText("Ortopedsko stanje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        getContentPane().add(jLabel27, gridBagConstraints);

        jLabel28.setText("Stanje probavnog sustava");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 14;
        getContentPane().add(jLabel28, gridBagConstraints);

        jLabel29.setText("Stanje disnog sustava");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        getContentPane().add(jLabel29, gridBagConstraints);

        jLabel30.setText("Stanje srca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        getContentPane().add(jLabel30, gridBagConstraints);

        jLabel31.setText("Hipersenzitivni");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        getContentPane().add(jLabel31, gridBagConstraints);

        jLabel32.setText("Dijabeticar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        getContentPane().add(jLabel32, gridBagConstraints);

        jLabel33.setText("Jedete li pretezno doma ili vani");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        getContentPane().add(jLabel33, gridBagConstraints);

        jLabel34.setText("Redovni obroci(dorucak rucak vecera)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        getContentPane().add(jLabel34, gridBagConstraints);

        jLabel35.setText("Koliko bezalkoholnih pica popijete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        getContentPane().add(jLabel35, gridBagConstraints);

        jLabel36.setText("Koliko kave i caja popijete dnevno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jLabel36, gridBagConstraints);

        jLabel37.setText("Koje stimulanse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel37, gridBagConstraints);

        jLabel38.setText("Stimulansi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel38, gridBagConstraints);

        jLabel39.setText("Unesite prosjecnu kolicinu alkohola koje popijete u danu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel39, gridBagConstraints);

        jLabel59.setText("Konzumiranje alkohola");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel59, gridBagConstraints);

        jLabel62.setText("Broj cigareta po danu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel62, gridBagConstraints);

        jLabel63.setText("Pusac");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel63, gridBagConstraints);
        getContentPane().add(boxPusac, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        getContentPane().add(boxAlkohol, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        getContentPane().add(boxStimulansi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        getContentPane().add(boxDijabeticar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        getContentPane().add(boxRedovniObroci, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 11;
        getContentPane().add(boxHipersenzitivan, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        getContentPane().add(txtBrojCigareta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtAlkohol, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtStimulansi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtKavaCaj, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBezalkoholnaPica, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtDomaVani, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtStanjeSrca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtStanjeDisnogPuta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtStanjeProbanogSustava, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtOrtopedskoStanje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtStanjeMisica, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtMentalnoStanje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtAlergije, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtReakcije, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtPrijasnjeOperacije, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        getContentPane().add(errorBrojCigareta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        getContentPane().add(errorAlkohol, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        getContentPane().add(errorStimulansi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        getContentPane().add(errorKavaCaj, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        getContentPane().add(errorBezalkoholnaPica, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        getContentPane().add(errorDomaVani, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 12;
        getContentPane().add(errorSrce, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 13;
        getContentPane().add(errorDisniSustav, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 14;
        getContentPane().add(errorProbavniSustav, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 15;
        getContentPane().add(errorOrtopedskoStanje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 16;
        getContentPane().add(errorStanjeMisica, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 17;
        getContentPane().add(errorMentalnoStanje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 18;
        getContentPane().add(errorAlergije, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 19;
        getContentPane().add(errorReakcije, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 20;
        getContentPane().add(errorOperacije, gridBagConstraints);

        jLabel64.setText("Zalbe, bolovi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel64, gridBagConstraints);

        jLabel65.setText("Povijest prijasnjih tretmana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel65, gridBagConstraints);

        jLabel66.setText("Doktor/Bolnica u kojoj ste bili prethodno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(jLabel66, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        getContentPane().add(errorZalbeBolovi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 5;
        getContentPane().add(errorPrijasnjiTretmani, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 9;
        getContentPane().add(errorPrijasnji, gridBagConstraints);

        txtZalbeBolovi.setColumns(20);
        txtZalbeBolovi.setRows(5);
        txtZalbeBolovi.setAutoscrolls(false);
        txtZalbeBolovi.setMinimumSize(new java.awt.Dimension(104, 64));
        jScrollPane1.setViewportView(txtZalbeBolovi);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        txtTretman.setColumns(20);
        txtTretman.setRows(5);
        txtTretman.setMinimumSize(new java.awt.Dimension(104, 64));
        jScrollPane2.setViewportView(txtTretman);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        txtDoktorBolnica.setColumns(20);
        txtDoktorBolnica.setRows(5);
        txtDoktorBolnica.setMinimumSize(new java.awt.Dimension(104, 64));
        jScrollPane3.setViewportView(txtDoktorBolnica);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        getContentPane().add(jScrollPane3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(errorUpisaSvega, gridBagConstraints);

        jButton1.setText("Unesite CRF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jButton1, gridBagConstraints);

        jLabel67.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        getContentPane().add(jLabel67, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 21;
        getContentPane().add(errorEmailPacijent, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtEmailPacijenta, gridBagConstraints);

        jLabel68.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        getContentPane().add(jLabel68, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        getContentPane().add(errorEmailRodaka, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtEmailRodaka, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean provjeraSlova(String unos, JLabel label) {

        if (unos.isEmpty()) {
            label.setText("*");
            return false;
        }
        for (char c : unos.toCharArray()) {
            if (Character.isDigit(c)) {
                label.setText("**");
                return false;
            }
        }
        label.setText("");

        return true;
    }

    private boolean provjeraBrojeva(String unos, JLabel label) {

        if (unos.isEmpty()) {
            label.setText("*");
            return false;
        }
        for (char c : unos.toCharArray()) {
            if (!Character.isDigit(c)) {
                label.setText("**");
                return false;
            }
        }
        label.setText("");
        return true;
    }

    private String unesiString(String unos, JLabel label) {
        if (provjeraSlova(unos, label)) {
            return unos;
        }
        return null;

    }

    private int unesiBroj(String unos, JLabel label) {
        int broj = 0;
        if (provjeraBrojeva(unos, label)) {
            broj = Integer.parseInt(unos);
        }
        return broj;

    }

    private float unesiFloat(String unos, JLabel label) {
        float broj = 0;
        try {
            broj = Float.parseFloat(unos);
        } catch (Exception e) {
            label.setText("**");
        }
        if (unos == null) {
            label.setText("*");
        }
        label.setText("");
        return broj;

    }

    private String unesiTelefon(String unos, JLabel label) {

        if (provjeraBrojeva(unos, label)) {
            return unos;
        }
        return null;

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //UBACIT LISTU ERRORA PA NA KRAJU SAMO PROVJERIS DA LI U NEKOJ NESTO PISE
        List<JLabel> greske = new ArrayList<JLabel>();
        int idPatient = unesiBroj(txtIDPacijenta.getText(), errorIDPacijent);
        greske.add(errorIDPacijent);
        if (!valid.provjeriIDPacijenta(idPatient)) {
            errorIDPacijent.setText("***");
        }

        int kucniBrojPrivremena = unesiBroj(txtKucniBrojPrivremeni.getText(), errorKucniBrojPrivremena);
        greske.add(errorKucniBrojPrivremena);

        String UlicaPrivremena = unesiString(txtUlicaPrivremena.getText(), errorUlicaPrivremena);
        greske.add(errorUlicaPrivremena);

        String KvartPrivremeni = unesiString(txtKvartPrivremeni.getText(), errorKvartPrivremeni);
        greske.add(errorKvartPrivremeni);

        String GradPrivremeni = unesiString(txtGradPrivremeni.getText(), errorGradPrivremeni);
        greske.add(errorGradPrivremeni);

        String DrzavaPrivremena = unesiString(txtDrzavaPrivremena.getText(), errorDrzavaPrivremena);
        greske.add(errorDrzavaPrivremena);

        int postanskiBrojPrivremeni = unesiBroj(txtPostanskiBrojPrivremeni.getText(), errorPostanskiBrojPrivremeni);
        greske.add(errorPostanskiBrojPrivremeni);

        int kucniBrojStalni = unesiBroj(txtKucniBrojStalni.getText(), errorKucniBrojStalni);
        greske.add(errorKucniBrojStalni);

        String UlicaStalna = unesiString(txtUlicaStalna.getText(), errorUlicaStalna);
        greske.add(errorUlicaStalna);

        String KvartStalni = unesiString(txtKvartStalni.getText(), errorKvartStalni);
        greske.add(errorKvartStalni);

        String GradStalni = unesiString(txtGradStalni.getText(), errorGradStalni);
        greske.add(errorGradStalni);

        String DrzavaStalna = unesiString(txtDrzavaStalna.getText(), errorDrzavaStalna);
        greske.add(errorDrzavaStalna);

        int postanskiBrojStalni = unesiBroj(txtPostanskiBrojStalni.getText(), errorPostanskiBrojStalni);
        greske.add(errorPostanskiBrojStalni);

        String BrojTelefonaPosaoPacijent = unesiTelefon(txtBrojTelefonaPosaoPacijenta.getText(), errorBrojTelefonaPosaoPacijent);
        greske.add(errorBrojTelefonaPosaoPacijent);

        String BrojTelefonaKucniPacijent = unesiTelefon(txtBrojTelefonaKucniPacijenta.getText(), errorBrojTelefonaKucniPacijent);
        greske.add(errorBrojTelefonaKucniPacijent);

        String BrojMobitelaPacijenta = unesiTelefon(txtBrojMobitelaPacijenta.getText(), errorBrojMobitelaPacijent);
        greske.add(errorBrojMobitelaPacijent);

        String PagerPacijenta = unesiTelefon(txtPagerPacijenta.getText(), errorPagerPacijent);
        greske.add(errorPagerPacijent);

        String FaxPacijenta = unesiTelefon(txtFaxPacijenta.getText(), errorFaxPacijenta);
        greske.add(errorFaxPacijenta);

        int kucniBrojRodaka = unesiBroj(txtKucniBrojRodaka.getText(), errorKucniBrojRodak);
        greske.add(errorKucniBrojRodak);

        String UlicaRodaka = unesiString(txtUlicaRodaka.getText(), errorUlicaRodak);
        greske.add(errorUlicaRodak);

        String KvartRodaka = unesiString(txtKvartRodaka.getText(), errorKvartRodak);
        greske.add(errorKvartRodak);

        String GradRodaka = unesiString(txtGradRodaka.getText(), errorGradRodak);
        greske.add(errorGradRodak);

        String DrzavaRodaka = unesiString(txtDrzavaRodaka.getText(), errorDrzavaRodak);
        greske.add(errorDrzavaRodak);

        int postanskiBroj = unesiBroj(txtPostanskiBrojRodaka.getText(), errorPostanskiBrojRodak);
        greske.add(errorPostanskiBrojRodak);

        String BrojTelefonaPosaoRodaka = unesiTelefon(txtBrojTelefonaPosaoRodak.getText(), errorBrojTelefonaPosaoRodak);
        greske.add(errorBrojTelefonaPosaoRodak);

        String BrojTelefonaKucniRodaka = unesiTelefon(txtBrojTelefonaKucniRodak.getText(), errorBrojTelefonaKucniRodak);
        greske.add(errorBrojTelefonaKucniRodak);

        String BrojMobitelaRodaka = unesiTelefon(txtBrojMobitelaRodak.getText(), errorBrojMobitelaRodak);
        greske.add(errorBrojMobitelaRodak);

        String PagerRodaka = unesiTelefon(txtPagerRodak.getText(), errorPagerRodak);
        greske.add(errorPagerRodak);

        String FaxRodaka = unesiTelefon(txtFaxRodak.getText(), errorFaxRodak);
        greske.add(errorFaxRodak);

        String BracniStatus = unesiString(txtBracniStatus.getText(), errorBracniStatus);
        greske.add(errorBracniStatus);

        int brojLjudi = unesiBroj(txtBrojLjudiKojeUzdrazavate.getText(), errorBrojLjudiKojeUzdrzavate);
        greske.add(errorBrojLjudiKojeUzdrzavate);

        float visina = unesiFloat(txtVisina.getText(), errorVisinađ);
        greske.add(errorVisinađ);

        float tezine = unesiFloat(txtTezina.getText(), errorTezina);
        greske.add(errorTezina);

        String KrvnaGrupa = unesiString(txtKrvnaGrupa.getText(), errorKrvnaGrupa);
        greske.add(errorKrvnaGrupa);

        String Zanimanje = unesiString(txtZanimanje.getText(), errorZanimanje);
        greske.add(errorZanimanje);

        float bruto = unesiFloat(txtBrutoDrustveniDohodak.getText(), errorBrutoGodisnjiDohodak);
        greske.add(errorBrutoGodisnjiDohodak);

        String Vegetarijanac;

        if (boxVegeterijanac.isSelected()) {
            Vegetarijanac = "Yes";
        } else {
            Vegetarijanac = "No";
        }
        String Pusac;
        float cigarete = 0;
        if (boxPusac.isSelected()) {
            Pusac = "Yes";
            cigarete = unesiFloat(txtBrojCigareta.getText(), errorBrojCigareta);
            greske.add(errorBrojCigareta);

        } else {
            Pusac = "No";
        }

        String Alkohol;
        float alkohol = 0;
        if (boxAlkohol.isSelected()) {
            Alkohol = "Yes";
            alkohol = unesiFloat(txtAlkohol.getText(), errorAlkohol);
            greske.add(errorAlkohol);

        } else {
            Alkohol = "No";
        }

        String Stimulansi;
        if (boxStimulansi.isSelected()) {
            Stimulansi = unesiString(txtStimulansi.getText(), errorStimulansi);
            greske.add(errorStimulansi);

        } else {
            Stimulansi = "No";
        }

        float kavaCaj = unesiFloat(txtKavaCaj.getText(), errorKavaCaj);
        greske.add(errorKavaCaj);

        float bezalkoholnaPica = unesiFloat(txtBezalkoholnaPica.getText(), errorBezalkoholnaPica);
        greske.add(errorBezalkoholnaPica);
        String RedovniObroci;

        if (boxRedovniObroci.isSelected()) {
            RedovniObroci = "Yes";
        } else {
            RedovniObroci = "No";
        }

        String EatOutHome = unesiString(txtDomaVani.getText(), errorDomaVani);
        if (!"Home".equals(EatOutHome) && !"Out".equals(EatOutHome)) {
            errorDomaVani.setText("Home/Out");

        }
        greske.add(errorDomaVani);

        String Dijabeticar;

        if (boxDijabeticar.isSelected()) {
            Dijabeticar = "Yes";
        } else {
            Dijabeticar = "No";
        }
        String Hiper;
        if (boxHipersenzitivan.isSelected()) {
            Hiper = "Yes";
        } else {
            Hiper = "No";
        }

        String StanjeSrca = unesiString(txtStanjeSrca.getText(), errorSrce);
        greske.add(errorSrce);

        String StanjeDisnogSustava = unesiString(txtStanjeDisnogPuta.getText(), errorDisniSustav);
        greske.add(errorDisniSustav);

        String StanjeProbavnogSustava = unesiString(txtStanjeProbanogSustava.getText(), errorProbavniSustav);
        greske.add(errorProbavniSustav);

        String OrtopedskoStanje = unesiString(txtOrtopedskoStanje.getText(), errorOrtopedskoStanje);
        greske.add(errorOrtopedskoStanje);

        String StanjeMisica = unesiString(txtStanjeMisica.getText(), errorStanjeMisica);
        greske.add(errorStanjeMisica);

        String MentalnoStanje = unesiString(txtMentalnoStanje.getText(), errorMentalnoStanje);
        greske.add(errorMentalnoStanje);

        String Alergije = unesiString(txtAlergije.getText(), errorAlergije);
        greske.add(errorAlergije);

        String ReakcijaString = unesiString(txtReakcije.getText(), errorReakcije);
        greske.add(errorReakcije);

        String PrijasnjeOperacije = unesiString(txtPrijasnjeOperacije.getText(), errorOperacije);
        greske.add(errorOperacije);

        String ZalbeBolovi = unesiString(txtZalbeBolovi.getText(), errorZalbeBolovi);
        greske.add(errorZalbeBolovi);

        String PrijasniTretman = unesiString(txtTretman.getText(), errorPrijasnjiTretmani);
        greske.add(errorPrijasnjiTretmani);

        String DoktorBolnica = unesiString(txtDoktorBolnica.getText(), errorPrijasnji);
        greske.add(errorPrijasnji);

        String EmailPacijenta = txtEmailPacijenta.getText();
        if (!valid.email_Validation(EmailPacijenta)) {
            errorEmailPacijent.setText("Nepostojeci");

        } else {
            errorEmailPacijent.setText("");

        }
        greske.add(errorEmailPacijent);

        String EmailRodaka = txtEmailRodaka.getText();
        if (!valid.email_Validation(EmailRodaka)) {
            errorEmailRodaka.setText("Nepostojeci");

        } else {
            errorEmailRodaka.setText("");

        }
        greske.add(errorEmailRodaka);

        boolean greska = false;

        for (JLabel l : greske) {
            if (!l.getText().equals("")) {
                greska = true;
                break;
            }
        }
        if (!greska) {

            Address StalnaAdresaPacijenta = new Address(kucniBrojStalni, UlicaStalna, KvartStalni, GradStalni, DrzavaStalna, postanskiBrojStalni);
            Address TrenutnaAdresaPacijenta = new Address(kucniBrojPrivremena, UlicaPrivremena, KvartPrivremeni, GradPrivremeni, DrzavaPrivremena, postanskiBrojPrivremeni);
            Contact KontaktPacijenta = new Contact(BrojTelefonaPosaoPacijent, BrojTelefonaKucniPacijent, BrojMobitelaPacijenta, PagerPacijenta, FaxPacijenta, EmailPacijenta);
            long trenutnaAdresaPacijenta = upis.unesiAddress(TrenutnaAdresaPacijenta);
            long stalnaAdresaPacijenta = upis.unesiAddress(StalnaAdresaPacijenta);
            long KontaktPacijentaID = upis.unesiNoviContact(KontaktPacijenta);
            upisUpdate.updatePacijenta(idPatient, stalnaAdresaPacijenta, KontaktPacijentaID, trenutnaAdresaPacijenta);

            long IDrodaka = selectIzBaze.dohvatiIDNextOfKin((long) idPatient);

            Address AdresaRodaka = new Address(kucniBrojRodaka, UlicaRodaka, KvartRodaka, GradRodaka, DrzavaRodaka, postanskiBroj);
            long adresaRodaka = upis.unesiAddress(AdresaRodaka);

            Contact KontaktRodaka = new Contact(BrojTelefonaPosaoRodaka, BrojTelefonaKucniRodaka, BrojMobitelaRodaka, PagerRodaka, FaxRodaka, EmailRodaka);
            long kontaktRodaka = upis.unesiNoviContact(KontaktRodaka);

            upisUpdate.updateNextOfKin(IDrodaka, adresaRodaka, kontaktRodaka);

            Record recZaupdate = new Record(idPatient, BracniStatus, brojLjudi, visina, tezine, KrvnaGrupa, Zanimanje, bruto, Vegetarijanac, Pusac, cigarete, Alkohol, alkohol, Stimulansi, kavaCaj, bezalkoholnaPica, RedovniObroci, EatOutHome, ZalbeBolovi, PrijasniTretman, DoktorBolnica, Dijabeticar, Hiper, StanjeSrca, StanjeDisnogSustava, StanjeProbavnogSustava, OrtopedskoStanje, StanjeMisica, MentalnoStanje, Alergije, ReakcijaString, PrijasnjeOperacije);
            upisUpdate.updateRecord(recZaupdate);

        } else {
            errorUpisaSvega.setText("Neuspjeli upis. *prazno polje  **krivi format  *** nepostojeci id");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICRF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxAlkohol;
    private javax.swing.JCheckBox boxDijabeticar;
    private javax.swing.JCheckBox boxHipersenzitivan;
    private javax.swing.JCheckBox boxPusac;
    private javax.swing.JCheckBox boxRedovniObroci;
    private javax.swing.JCheckBox boxStimulansi;
    private javax.swing.JCheckBox boxVegeterijanac;
    private javax.swing.JLabel errorAlergije;
    private javax.swing.JLabel errorAlkohol;
    private javax.swing.JLabel errorBezalkoholnaPica;
    private javax.swing.JLabel errorBracniStatus;
    private javax.swing.JLabel errorBrojCigareta;
    private javax.swing.JLabel errorBrojLjudiKojeUzdrzavate;
    private javax.swing.JLabel errorBrojMobitelaPacijent;
    private javax.swing.JLabel errorBrojMobitelaRodak;
    private javax.swing.JLabel errorBrojTelefonaKucniPacijent;
    private javax.swing.JLabel errorBrojTelefonaKucniRodak;
    private javax.swing.JLabel errorBrojTelefonaPosaoPacijent;
    private javax.swing.JLabel errorBrojTelefonaPosaoRodak;
    private javax.swing.JLabel errorBrutoGodisnjiDohodak;
    private javax.swing.JLabel errorDisniSustav;
    private javax.swing.JLabel errorDomaVani;
    private javax.swing.JLabel errorDrzavaPrivremena;
    private javax.swing.JLabel errorDrzavaRodak;
    private javax.swing.JLabel errorDrzavaStalna;
    private javax.swing.JLabel errorEmailPacijent;
    private javax.swing.JLabel errorEmailRodaka;
    private javax.swing.JLabel errorFaxPacijenta;
    private javax.swing.JLabel errorFaxRodak;
    private javax.swing.JLabel errorGradPrivremeni;
    private javax.swing.JLabel errorGradRodak;
    private javax.swing.JLabel errorGradStalni;
    private javax.swing.JLabel errorIDPacijent;
    private javax.swing.JLabel errorKavaCaj;
    private javax.swing.JLabel errorKrvnaGrupa;
    private javax.swing.JLabel errorKucniBrojPrivremena;
    private javax.swing.JLabel errorKucniBrojRodak;
    private javax.swing.JLabel errorKucniBrojStalni;
    private javax.swing.JLabel errorKvartPrivremeni;
    private javax.swing.JLabel errorKvartRodak;
    private javax.swing.JLabel errorKvartStalni;
    private javax.swing.JLabel errorMentalnoStanje;
    private javax.swing.JLabel errorOperacije;
    private javax.swing.JLabel errorOrtopedskoStanje;
    private javax.swing.JLabel errorPagerPacijent;
    private javax.swing.JLabel errorPagerRodak;
    private javax.swing.JLabel errorPostanskiBrojPrivremeni;
    private javax.swing.JLabel errorPostanskiBrojRodak;
    private javax.swing.JLabel errorPostanskiBrojStalni;
    private javax.swing.JLabel errorPrijasnji;
    private javax.swing.JLabel errorPrijasnjiTretmani;
    private javax.swing.JLabel errorProbavniSustav;
    private javax.swing.JLabel errorReakcije;
    private javax.swing.JLabel errorSrce;
    private javax.swing.JLabel errorStanjeMisica;
    private javax.swing.JLabel errorStimulansi;
    private javax.swing.JLabel errorTezina;
    private javax.swing.JLabel errorUlicaPrivremena;
    private javax.swing.JLabel errorUlicaRodak;
    private javax.swing.JLabel errorUlicaStalna;
    private javax.swing.JLabel errorUpisaSvega;
    private javax.swing.JLabel errorVisinađ;
    private javax.swing.JLabel errorZalbeBolovi;
    private javax.swing.JLabel errorZanimanje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtAlergije;
    private javax.swing.JTextField txtAlkohol;
    private javax.swing.JTextField txtBezalkoholnaPica;
    private javax.swing.JTextField txtBracniStatus;
    private javax.swing.JTextField txtBrojCigareta;
    private javax.swing.JTextField txtBrojLjudiKojeUzdrazavate;
    private javax.swing.JTextField txtBrojMobitelaPacijenta;
    private javax.swing.JTextField txtBrojMobitelaRodak;
    private javax.swing.JTextField txtBrojTelefonaKucniPacijenta;
    private javax.swing.JTextField txtBrojTelefonaKucniRodak;
    private javax.swing.JTextField txtBrojTelefonaPosaoPacijenta;
    private javax.swing.JTextField txtBrojTelefonaPosaoRodak;
    private javax.swing.JTextField txtBrutoDrustveniDohodak;
    private javax.swing.JTextArea txtDoktorBolnica;
    private javax.swing.JTextField txtDomaVani;
    private javax.swing.JTextField txtDrzavaPrivremena;
    private javax.swing.JTextField txtDrzavaRodaka;
    private javax.swing.JTextField txtDrzavaStalna;
    private javax.swing.JTextField txtEmailPacijenta;
    private javax.swing.JTextField txtEmailRodaka;
    private javax.swing.JTextField txtFaxPacijenta;
    private javax.swing.JTextField txtFaxRodak;
    private javax.swing.JTextField txtGradPrivremeni;
    private javax.swing.JTextField txtGradRodaka;
    private javax.swing.JTextField txtGradStalni;
    private javax.swing.JTextField txtIDPacijenta;
    private javax.swing.JTextField txtKavaCaj;
    private javax.swing.JTextField txtKrvnaGrupa;
    private javax.swing.JTextField txtKucniBrojPrivremeni;
    private javax.swing.JTextField txtKucniBrojRodaka;
    private javax.swing.JTextField txtKucniBrojStalni;
    private javax.swing.JTextField txtKvartPrivremeni;
    private javax.swing.JTextField txtKvartRodaka;
    private javax.swing.JTextField txtKvartStalni;
    private javax.swing.JTextField txtMentalnoStanje;
    private javax.swing.JTextField txtOrtopedskoStanje;
    private javax.swing.JTextField txtPagerPacijenta;
    private javax.swing.JTextField txtPagerRodak;
    private javax.swing.JTextField txtPostanskiBrojPrivremeni;
    private javax.swing.JTextField txtPostanskiBrojRodaka;
    private javax.swing.JTextField txtPostanskiBrojStalni;
    private javax.swing.JTextField txtPrijasnjeOperacije;
    private javax.swing.JTextField txtReakcije;
    private javax.swing.JTextField txtStanjeDisnogPuta;
    private javax.swing.JTextField txtStanjeMisica;
    private javax.swing.JTextField txtStanjeProbanogSustava;
    private javax.swing.JTextField txtStanjeSrca;
    private javax.swing.JTextField txtStimulansi;
    private javax.swing.JTextField txtTezina;
    private javax.swing.JTextArea txtTretman;
    private javax.swing.JTextField txtUlicaPrivremena;
    private javax.swing.JTextField txtUlicaRodaka;
    private javax.swing.JTextField txtUlicaStalna;
    private javax.swing.JTextField txtVisina;
    private javax.swing.JTextArea txtZalbeBolovi;
    private javax.swing.JTextField txtZanimanje;
    // End of variables declaration//GEN-END:variables
}
