/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import RadSBazom.Chart;
import RadSBazom.NextOfKin;
import RadSBazom.Patient;
import RadSBazom.Record;
import RadSBazom.UpisivanjeUBazu;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javaprojekt.Konzola;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.regexp.joni.encoding.CharacterType;

/**
 *
 * @author Bruno-PC
 */
public class GUIMRF extends javax.swing.JFrame {

    UpisivanjeUBazu upis = new UpisivanjeUBazu();
    Konzola kon = new Konzola();

    /**
     * Creates new form GUIMRF
     */
    public GUIMRF() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIme = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSrednjeIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOIB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radioButtonMale = new javax.swing.JRadioButton();
        radioButtonFemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtDatumRodenja = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtImeRodaka = new javax.swing.JTextField();
        d = new javax.swing.JLabel();
        srednjeImeRodaka = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrezimeRodaka = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtOdnos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        errorImePacijenta = new javax.swing.JLabel();
        krivoIme = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        krivoSrednjeIme = new javax.swing.JLabel();
        krivoPrezime = new javax.swing.JLabel();
        kriviOIB = new javax.swing.JLabel();
        oznaciteSpol = new javax.swing.JLabel();
        greskaKratka = new javax.swing.JLabel();
        krivoImeRodaka = new javax.swing.JLabel();
        krivoPrezimeRodaka = new javax.swing.JLabel();
        krivoPrezimeRodakaPravo = new javax.swing.JLabel();
        kriviOdnos = new javax.swing.JLabel();
        krivaKratka = new javax.swing.JLabel();
        krivoIMERodaka = new javax.swing.JLabel();
        greskaDatum = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtKontakttelefon1 = new javax.swing.JTextField();
        txtKontaktTelefon2 = new javax.swing.JTextField();
        errorKontakt1 = new javax.swing.JLabel();
        errorKontakt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MRF");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MRF");
        jLabel1.setToolTipText("");

        jButton1.setText("Spremiti");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel2.setText("Ime pacijenta:");

        txtIme.setToolTipText("");
        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        jLabel3.setText("Srednje ime pacijenta:");

        jLabel4.setText("Prezime pacijenta");

        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        jLabel5.setText("OIB pacijenta:");

        jLabel6.setText("Spol");

        buttonGroup1.add(radioButtonMale);
        radioButtonMale.setText("Male");

        buttonGroup1.add(radioButtonFemale);
        radioButtonFemale.setText("Female");

        jLabel7.setText("Datum rodenja (mm.dd.yyyy.)");

        jLabel8.setText("Kratka izjava o stanju");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setText("Ime rodaka:");

        d.setText("Srednje ime rodaka:");

        jLabel11.setText("Prezime rodaka:");

        txtPrezimeRodaka.setToolTipText("");

        jLabel12.setText("Odnos s pacijentom");

        txtOdnos.setToolTipText("");

        errorImePacijenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorImePacijenta.setForeground(new java.awt.Color(255, 51, 51));

        kriviOIB.setToolTipText("");

        jLabel10.setText("Kontakt telefon 1");

        jLabel15.setText("Kontakt telefon 2");

        txtKontaktTelefon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKontaktTelefon2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(d)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel9))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(srednjeImeRodaka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                                .addComponent(txtImeRodaka, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPrezimeRodaka)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel15))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtOdnos, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                                .addComponent(txtKontakttelefon1)
                                                .addComponent(txtKontaktTelefon2))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(krivoIMERodaka, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(krivoImeRodaka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(krivoPrezimeRodaka, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(kriviOdnos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(krivoPrezimeRodakaPravo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(errorKontakt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(errorKontakt2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(153, 153, 153)
                            .addComponent(greskaKratka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel1))
                                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txtSrednjeIme))
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrezime)
                                    .addComponent(txtOIB)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioButtonMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioButtonFemale))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatumRodenja)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(krivoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(56, 56, 56)
                                .addComponent(errorImePacijenta))
                            .addComponent(krivoSrednjeIme, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(krivaKratka, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(krivoPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kriviOIB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(68, 68, 68))
                                            .addComponent(oznaciteSpol, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(greskaDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(krivoIme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(errorImePacijenta)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(krivoSrednjeIme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtSrednjeIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krivoPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kriviOIB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radioButtonMale)
                    .addComponent(radioButtonFemale)
                    .addComponent(oznaciteSpol, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDatumRodenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greskaDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greskaKratka, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krivaKratka, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtImeRodaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krivoImeRodaka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krivoIMERodaka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(krivoPrezimeRodaka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d)
                        .addComponent(srednjeImeRodaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(krivoPrezimeRodakaPravo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtPrezimeRodaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kriviOdnos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtOdnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKontakttelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorKontakt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtKontaktTelefon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorKontakt2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed


    }//GEN-LAST:event_txtImeActionPerformed

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private boolean provjeraBrojeva(String unos, JLabel label) {
        if (unos.isEmpty() && !label.equals(krivoSrednjeIme)) {
            label.setText("Prazno polje");
            return false;
        }
        for (char c : unos.toCharArray()) {
            if (!Character.isDigit(c)) {
                label.setText("Krivi unos!");
                return false;
            }
        }
        label.setText("");
        return true;
    }

    private boolean provjeraSlova(String unos, JLabel label) {
        if (unos.isEmpty() && !label.equals(krivoSrednjeIme)) {
            label.setText("Prazno polje");
            return false;
        }
        for (char c : unos.toCharArray()) {
            if (Character.isDigit(c)) {
                label.setText("Krivi unos!");
                return false;
            }
        }
        if (unos.length() >= 50) {
            label.setText("Najvise 50 znakova");
        }
        label.setText("");
        return true;

    }

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        String Ime = txtIme.getText();
        boolean ime = provjeraSlova(Ime, krivoIme);
        String Prezime = txtPrezime.getText();
        boolean prezime = provjeraSlova(Prezime, krivoPrezime);
        String DrugoIme = txtSrednjeIme.getText();
        boolean drugoIme = provjeraSlova(DrugoIme, krivoSrednjeIme);

        boolean oib = true;
        if (txtOIB.getText().isEmpty()) {
            kriviOIB.setText("Prazno polje!");
        }
        String OIB = txtOIB.getText();
        for (char c : OIB.toCharArray()) {
            if (!Character.isDigit(c)) {
                kriviOIB.setText("Krivi unos oib se satoji od 13 brojeva!");
                oib = false;
                break;

            }

            if (!OIB.matches("[0-9]{13}")) {
                kriviOIB.setText("Krivi unos oib se satoji od 13 brojeva!");
                oib = false;
            }

            if (oib) {
                kriviOIB.setText("");
            }

        }
        String spol = null;
        if (!(radioButtonFemale.isSelected() || radioButtonMale.isSelected())) {
            oznaciteSpol.setText("Oznacite spol");
        } else {
            if (radioButtonFemale.isSelected()) {
                spol = "Female";
                oznaciteSpol.setText("");
            } else if (radioButtonMale.isSelected()) {
                spol = "Male";
                oznaciteSpol.setText("");
            }
        }
        String KratkaIzjava = jTextArea1.getText();
        boolean kratkaIzjava = true;
        if (jTextArea1.getText().isEmpty()) {
            krivaKratka.setText("Prazno polje");
            kratkaIzjava = false;
        }

        if (kratkaIzjava) {
            krivaKratka.setText("");
        }

        String ImeRodaka = txtImeRodaka.getText();
        boolean imeRodaka = provjeraSlova(ImeRodaka, krivoIMERodaka);

        String SrednjeImeRodaka = srednjeImeRodaka.getText();
        boolean srednjeImeRodaka = provjeraSlova(SrednjeImeRodaka, krivoPrezimeRodaka);

        String PrezimeRodaka = txtPrezimeRodaka.getText();
        boolean prezimeRodaka = provjeraSlova(PrezimeRodaka, krivoPrezimeRodakaPravo);

        String OdnosSPacijentom = txtOdnos.getText();
        boolean odnosSPacijentom = provjeraSlova(OdnosSPacijentom, kriviOdnos);

        boolean datum = true;

        DateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        Date date = null;
        try {
            LocalDate dateLocal = LocalDate.parse(txtDatumRodenja.getText(), DateTimeFormatter.ofPattern("dd.MM.yyyy."));
            LocalDate danasnji = LocalDate.now();
            if (!dateLocal.isBefore(danasnji)) {
                greskaDatum.setText("Unesite datum u proslosti.");
                datum = false;
            }
            date = Date.valueOf(dateLocal);
        } catch (Exception ex) {
            greskaDatum.setText("Datum je u krivom formatu. (dd.MM.yyyy.)");
            datum = false;
        }

        if (datum) {
            greskaDatum.setText("");
        }

        String Kontakt1 = txtKontakttelefon1.getText();
        boolean kontakt1 = provjeraBrojeva(Kontakt1, errorKontakt1);

        String Kontakt2 = txtKontaktTelefon2.getText();
        boolean kontak2 = provjeraBrojeva(Kontakt2, errorKontakt2);

        if (datum && odnosSPacijentom && prezimeRodaka && srednjeImeRodaka && imeRodaka && kratkaIzjava && oib && ime && prezime && drugoIme && kontakt1 && kontak2) {
            NextOfKin rodak = new NextOfKin(ImeRodaka, SrednjeImeRodaka, PrezimeRodaka, OdnosSPacijentom);
            long rodaka = upis.unesiNoviNextOfKin(rodak);
            Patient pacijent = new Patient(Ime, DrugoIme, Prezime, spol, date, OIB, (int) rodaka);
            long pacijentid = upis.unesiNovogPacijenta(pacijent);

            Date danasnjidan = kon.danasnjiDan();

            Chart karton = new Chart((int) pacijentid);

            upis.unesiChart(karton);

            Record rekord = new Record(danasnjidan, (int) pacijentid, KratkaIzjava, Kontakt1, Kontakt2);
            upis.unesiRecord(rekord);
            this.dispose();
        }


    }//GEN-LAST:event_jButton1MousePressed

    private void txtKontaktTelefon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontaktTelefon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontaktTelefon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMRF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel d;
    private javax.swing.JLabel errorImePacijenta;
    private javax.swing.JLabel errorKontakt1;
    private javax.swing.JLabel errorKontakt2;
    private javax.swing.JLabel greskaDatum;
    private javax.swing.JLabel greskaKratka;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel krivaKratka;
    private javax.swing.JLabel kriviOIB;
    private javax.swing.JLabel kriviOdnos;
    private javax.swing.JLabel krivoIMERodaka;
    private javax.swing.JLabel krivoIme;
    private javax.swing.JLabel krivoImeRodaka;
    private javax.swing.JLabel krivoPrezime;
    private javax.swing.JLabel krivoPrezimeRodaka;
    private javax.swing.JLabel krivoPrezimeRodakaPravo;
    private javax.swing.JLabel krivoSrednjeIme;
    private javax.swing.JLabel oznaciteSpol;
    private javax.swing.JRadioButton radioButtonFemale;
    private javax.swing.JRadioButton radioButtonMale;
    private javax.swing.JTextField srednjeImeRodaka;
    private javax.swing.JTextField txtDatumRodenja;
    private javax.swing.JFormattedTextField txtIme;
    private javax.swing.JTextField txtImeRodaka;
    private javax.swing.JTextField txtKontaktTelefon2;
    private javax.swing.JTextField txtKontakttelefon1;
    private javax.swing.JTextField txtOIB;
    private javax.swing.JTextField txtOdnos;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtPrezimeRodaka;
    private javax.swing.JTextField txtSrednjeIme;
    // End of variables declaration//GEN-END:variables
}
